version: '3.8'
services:
  miallo-db:
    image: mongo
    container_name: itmo-web-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=panteleevya
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27018:27017"
